print("this is intro class")
x=int(input("enter the number"))
y=int(input("enter the number"))
print("addition is",x+y)
print("subtraction is",x-y)
print("multiplcation is",x*y)
print("divition is",x/y)
print("remander is",x%y)
